version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    networks:
      - your-network
    volumes:
      - ./mysql-db:/var/lib/mysql

networks:
  your-network:
    external: true
  traefik:
    external: true
