version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - GIT_REPO=${GIT_REPO}
        - GIT_BRANCH=${GIT_BRANCH}
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PROJECT_NAME=${PROJECT_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    expose:
      - ${PORT}
    logging:
      driver: json-file
      options:
        max-size: 50m
    command: "/usr/bin/gunicorn --workers 3 --bind :${PORT} ${PROJECT_NAME}.wsgi:application"
