version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - GIT_REPO: ${GIT_REPO}
        - GIT_BRANCH: ${GIT_BRANCH}
        - PROJECT_NAME: ${PROJECT_NAME}
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - PROJECT_NAME=${PROJECT_NAME}
