version: "3.7"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    networks:
      - your-network
    volumes:
      - ./mysql-db:/var/lib/mysql
  app:
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_ID}-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${APP_ID}-router.entrypoints=web"
      - "traefik.http.middlewares.${APP_ID}-redirect-middleware.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_ID}-router.middlewares=${APP_ID}-redirect-middleware"
      - "traefik.http.routers.${APP_ID}-secure-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${APP_ID}-secure-router.entrypoints=websecure"
      - "traefik.http.routers.${APP_ID}-secure-router.tls=true"
      - "traefik.http.routers.${APP_ID}-secure-router.tls.certresolver=lets-encrypt"
      - "traefik.http.services.${APP_ID}-service.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${APP_ID}-secure-router.service=${APP_ID}-service"
    volumes:
      - ${SOURCE_CODE_PATH}://home/apps/${PROJECT_NAME}
